name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build Library and Demo
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Build Library and Demo
        run:
          chmod a+x auto-build.sh &&
          ./auto-build.sh &&
          pwd &&
          cp Project/Demo/doc/Memory.json Project/Demo/target &&
          cd Project/Demo/target &&
          ./Demo
